# Copyright (c) 2025 Xiaomi Corporation
# SPDX-License-Identifier: Apache-2.0

name: Publish to GitHub Pages

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          pattern: output-*
          path: output/
          merge-multiple: true

      - name: Copy index.html to output
        run: |
          cp site/index.html output/
          ls -la output/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
