name: Publish

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          pattern: output-*
          path: output/
          merge-multiple: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build page
        run: |
          cd page
          npm install
          npm run build

      - name: Copy built site to output
        run: |
          cp -r page/dist/* output/
          ls -la output/

      - name: Generate boards list
        run: |
          find output -name "*.json" -type f | sed 's|output/||' | sort > output/boards.txt
          cat output/boards.txt

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
